// Code generated by goctl. DO NOT EDIT!
// Source: trans.proto

package server

import (
	"context"

	"xa/trans/internal/logic"
	"xa/trans/internal/svc"
	"xa/trans/trans"
)

type TransServer struct {
	svcCtx *svc.ServiceContext
	trans.UnimplementedTransServer
}

func NewTransServer(svcCtx *svc.ServiceContext) *TransServer {
	return &TransServer{
		svcCtx: svcCtx,
	}
}

func (s *TransServer) TransOutXa(ctx context.Context, in *trans.AdjustInfo) (*trans.Response, error) {
	l := logic.NewTransOutXaLogic(ctx, s.svcCtx)
	return l.TransOutXa(in)
}

func (s *TransServer) TransInXa(ctx context.Context, in *trans.AdjustInfo) (*trans.Response, error) {
	l := logic.NewTransInXaLogic(ctx, s.svcCtx)
	return l.TransInXa(in)
}
